version: "3.4"
services:
  frontend:
    image: homeless-frontend
    container_name: homeless-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - homeless-network

networks:
  homeless-network:
    external: true