version: "3.4"
services:
  frontend:
    image: node:18.16.0-slim
    container_name: homeless_frontend
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 3000:3000
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true
    networks:
      - homeless-network

networks:
  homeless-network:
    external: true